'''
Author: Hanqing Zhu(hqzhu@utexas.edu)
Date: 1969-12-31 18:00:00
LastEditTime: 2022-04-09 00:23:04
LastEditors: Hanqing Zhu(hqzhu@utexas.edu)
Description: 
FilePath: /projects/ELight/configs/cifar10/vgg/reorder.py
'''
